# Generated by Django 5.2.1 on 2025-05-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_blocklist',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='token_blocklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='token_blocklist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
